"""黄金基准数据"""

from .golden_data import (
    STRAIN_GOLDEN,
    TEMP_GOLDEN_S_EFF, TEMP_GOLDEN_T_BASE, TEMP_GOLDEN_R2,
    TEMP_REGRESSION_ATOL, TEMP_TBASE_ATOL, TEMP_R2_ATOL,
    STRAIN_K_TOL, STRAIN_R2_TOL, STRAIN_NL_TOL, STRAIN_RP_TOL, STRAIN_HY_TOL,
)

__all__ = [
    "STRAIN_GOLDEN",
    "TEMP_GOLDEN_S_EFF", "TEMP_GOLDEN_T_BASE", "TEMP_GOLDEN_R2",
    "TEMP_REGRESSION_ATOL", "TEMP_TBASE_ATOL", "TEMP_R2_ATOL",
    "STRAIN_K_TOL", "STRAIN_R2_TOL", "STRAIN_NL_TOL", "STRAIN_RP_TOL", "STRAIN_HY_TOL",
]
